version: 2
jobs:
  minecraft_server:
    docker:
      - image: circleci/buildpack-deps:18.04
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build image
          command: docker build -t mc:$CIRCLE_BUILD_NUM minecraft-server

workflows:
  version: 2
  build:
    jobs:
      - minecraft_server
