# This composition is known to work on a Swarm cluster consisting of
# 3 VM nodes with 1GB allocated to each.
version: '3'

services:
  master:
    image: itzg/elasticsearch
    environment:
      UNICAST_HOSTS: master
      MIN_MASTERS: 1
      ES_JAVA_OPTS: -Xms756m -Xmx756m
      TYPE: NON_DATA
    ports:
      - "9200:9200"
      - "9300:9300"
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
  data:
    image: itzg/elasticsearch
    deploy:
      mode: global
      update_config:
        parallelism: 1
    environment:
      TYPE: DATA
      UNICAST_HOSTS: master
      ES_JAVA_OPTS: -Xms512m -Xmx512m
  kibana:
    image: kibana
    ports:
      - "5601:5601"
    environment:
      ELASTICSEARCH_URL: http://master:9200
