version: '3'

services:
  master:
    build: .
    environment:
      TYPE: MASTER
      UNICAST_HOSTS: master
      MIN_MASTERS: 1
  data:
    build: .
    environment:
      TYPE: DATA
      UNICAST_HOSTS: master
  gateway:
    build: .
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      TYPE: GATEWAY
      UNICAST_HOSTS: master
  ingest:
    build: .
    ports:
      - "9222:9200"
    environment:
      TYPE: INGEST
      UNICAST_HOSTS: master
  kibana:
    image: kibana:5.5.1
    ports:
      - "5601:5601"
    environment:
      ELASTICSEARCH_URL: http://gateway:9200
