version: '3.7'

services:
  mc:
    image: itzg/minecraft-server
    environment:
      EULA: "true"
      TYPE: PAPER
      VERSION: 1.9.4
    command: --noconsole
    ports:
      - 25565:25565
    volumes:
      - mc-paper:/data

volumes:
  mc-paper: